repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
        args: ['--maxkb=10000']
      - id: detect-private-key
      - id: check-merge-conflict

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.38.0
    hooks:
      - id: eslint
        files: \.(js|jsx|ts|tsx)$
        types: [file]
        additional_dependencies:
          - eslint
          - typescript
          - '@typescript-eslint/eslint-plugin'
          - '@typescript-eslint/parser'
          - eslint-plugin-react

  - repo: local
    hooks:
      - id: prevent-large-files
        name: Prevent Large Files Over 90MB
        entry: bash .githooks/prevent_large_files.sh
        language: system
        types: [file]
      
      - id: mcp-router-check
        name: Check for hardcoded MCP router URLs
        entry: bash -c "! grep -n 'localhost:3000' $(git diff --cached --name-only | grep -E '\.(js|jsx|ts|tsx)$') 2>/dev/null | grep -v 'process.env'"
        language: system
        files: \.(js|jsx|ts|tsx)$
        types: [file]

      - id: ts-type-check
        name: TypeScript Type Check
        entry: npx tsc --noEmit
        language: system
        pass_filenames: false
        types: [ts, tsx]